version: '3'

services:
  ros-encoder:
    image: ghcr.io/rosblox/ros-encoder:humble
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    volumes:
      - /tmp:/tmp
    command: su - ros --whitelist-environment=ROS_DOMAIN_ID /run.sh
